version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: MyDemoShop
      MYSQL_USER: MyDemoShopAdmin
      MYSQL_PASSWORD: Pa$$w0rd77